# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  ImGui_config = debug
  Discord_config = debug
  ODVM_config = debug
  Sandbox_config = debug
endif
ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  ImGui_config = release
  Discord_config = release
  ODVM_config = release
  Sandbox_config = release
endif
ifeq ($(config),dist)
  GLFW_config = dist
  Glad_config = dist
  ImGui_config = dist
  Discord_config = dist
  ODVM_config = dist
  Sandbox_config = dist
endif

PROJECTS := GLFW Glad ImGui Discord ODVM Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C ODVM/libs/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C ODVM/libs/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C ODVM/libs/ImGui -f Makefile config=$(ImGui_config)
endif

Discord:
ifneq (,$(Discord_config))
	@echo "==== Building Discord ($(Discord_config)) ===="
	@${MAKE} --no-print-directory -C ODVM/libs/Discord -f Makefile config=$(Discord_config)
endif

ODVM: GLFW Glad ImGui Discord
ifneq (,$(ODVM_config))
	@echo "==== Building ODVM ($(ODVM_config)) ===="
	@${MAKE} --no-print-directory -C ODVM -f Makefile config=$(ODVM_config)
endif

Sandbox: ODVM GLFW Discord Glad ImGui
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C ODVM/libs/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C ODVM/libs/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C ODVM/libs/ImGui -f Makefile clean
	@${MAKE} --no-print-directory -C ODVM/libs/Discord -f Makefile clean
	@${MAKE} --no-print-directory -C ODVM -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   Discord"
	@echo "   ODVM"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"